### ISSUE TITLE
Writing zip stream to a socket

### ISSUE THREAD

**Issue by themolecule** [stachenov/quazip#47] opened 2019-11-01 13:00 UTC
Hello, I apologize for crossing threads previously.

I would like to write zip data to a network stream/socket.

What I have so far:

```
QBuffer _zipBuffer;	
QuaZIODevice _zipDevice(&_zipBuffer);
QuaZip _zipObject(&_zipDevice);

QuaZipFile _zipFile(&_zipObject);
QString f2("some/path/to/a/file.txt");

if (! (	_zipObject.open(QuaZip::mdCreate)	&&
		_zipDevice.open(QIODevice::WriteOnly)	&&
		_zipBuffer.open(QIODevice::ReadWrite)	&&
		_zipFile.open(QIODevice::WriteOnly, QuaZipNewInfo(f2))
{
	//device(s) could not be opened, report an error
}
else
{
	//device is open, fetch data
	fetchDataChunk();
}

//...

//then after fetchDataChunk() returns with data...

_zipDevice.write( qbytearraydata );
//_zipFile.write( qbytearraydata );	//makes sense, but doesn't work

//...

//then after issuing a request for more data or knowing that there is no more data...

_zipBuffer.seek(0);
QByteArray data = _zipBuffer.readAll();
_socket.write(data);

```

I'm getting data back from the buffer, but saving the data to file (using curl, for instance) results in an invalid zip file.

I feel like I'm missing something here, and have had trouble figuring it out.

**Comment by stachenov** [comment] 2019-11-01 13:15
As I've already mentioned, QuaZIODevice should *not* be used here. It has absolutely nothing to do with ZIP files (except that it uses the same compression algorithm, which is irrelevant here). You'd want to use it, for example, if you needed to send some data over a TCP connection between two pieces of your software. It's for compressing *streams*, not files.

If you use a QBuffer, just write a QuaZip directly into it.

**Comment by themolecule** [comment] 2019-11-01 13:19
And I would write to a QuaZipFile?

That's the problem, is that I don't have files.  The data may be coming from a database or some other abstraction.  There is no file name, there is no disk.  I'm inventing a filename using a database ID.  So it feels like a stream and not a file, as data will come in chunks from a remote resource.

**Comment by stachenov** [comment] 2019-11-01 14:02
I've asked you to read the previous issue. You haven't. Otherwise you'd understand what QuaZIODevice is, and why you shouldn't have used it in the first place.

I've asked you to do some research before opening a new issue. You haven't either. (Judging by how quickly you opened this, you haven't even *tried*.) Because otherwise you would understand what these classes are, what kind of abstraction they provide. You'd even probably quickly find in the test suite an example of code that does exactly what you need.

Closing this issue for being a pointless discussion.

**Closed by stachenov** 2019-11-01 14:02 UTC

**Comment by themolecule** [comment] 2019-11-02 06:49
I've been reading it.  Sorry to bother you.  I will keep looking.  I've read the documentation up and down and have removed QuaZIODevice from my code.  It doesn't take that long to read code or documentation.

The test suite does not provide a method for writing chunked (network) data to a stream as raw data and then reading that as zipped data with file names.  I am sure I'm missing something in my code, but your response is pretty harsh.

If you want your library to live, you will need to be a little bit nicer to those who are interpreting it.  We are all coming from different contexts.

thanks @stachenov for contributing to the open source community.

**Comment by stachenov** [comment] 2019-11-04 09:05
Of course it's harsh. It was intended to be so. It doesn't have anything to do with contexts or experience. It's because you fail to understand how things work. You obviously lack general knowledge of OOP and Qt. It doesn't have anything to do with QuaZIP. And it's not my job to teach you these things.

Frankly, I don't care whether my library lives or dies. I wrote it because I needed it, and I shared it because I believe it's nice that anyone can use it instead of re-inventing the same wheel again and again. If anyone needs any help with the library, I'm willing to help as long as they are ready to help themselves too. Not because I must, but because I believe it's the right thing to do.

But you keep asking questions that doesn't make any sense. That is beyond any help. For example, you mention “writing chunked (network) data”. How is that any different from writing to a file? What is the signature of `QuaZip` constructors? They don't accept `QFile` or anything like that. They accept `QIODevice` because it's the single abstraction behind all kinds of I/O devices in Qt. How is writing to a file any different than writing to a network socket? In exactly one way: writing to a socket is sequential, writing to a file is not (you can `seek` back). So, if you had understand these basic things, your question should have been very simple from the very beginning: “Does QuaZIP support writing ZIP files into sequential `QIODevice`s?”. The answer is also very simple: it does. In fact, this answer is even in the FAQ! Which you claim to have read. So writing into a socket is absolutely no different than writing to a file. Just as one would expect in OOP.

The test suite also *does* provide an example that tests this very thing: writing into a sequential device. It even uses a socket for that! Surely it only writes 4 bytes in one `write()` call into one file, but how is that any different from writing lots of chunks into different files? Nohow.

But instead of asking simple questions that boil down to simple answers, you ask something along the lines “How to do X?”, expecting ready-to-use code in response. This is not how it works. Then again, if you have some code that *doesn't work*, it's *your* responsibility to boil it down to a minimal, complete example that can be compiled and run right out of the box and that clearly demonstrates the problem you're experiencing. Instead you post random pieces of code that someone is supposed to read through, understand what exactly do you need, and turn that mess into perfect code? Sorry, but that's not how it works either.

**Comment by themolecule** [comment] 2019-12-29 01:03
This was much more easily accomplished using libarchive, which offers more options and the API is much clearer, as well as documentation.

I'm annoyed at how you've responded, and thought that letting it sit for a while I would get over it, but after solving my code much more elegantly using libarchive, I have to come back to respond that your library is not well written, and the documentation is poor at best.  You have covered some cases in your documentation, but the specific sequencing of calls is not outlined, and the way calls are made is not clear.  You can do better, or you should un-post this code so other people don't have issues understanding it.

I had an easier time linking the C libraries from libarchive, and asking questions of the community around it, and ultimately gained the ability to encode into many different formats aside from zip without worrying about sequencing of calls or flags.

Wrapping it for Qt was not difficult.

I hope that in the future you care about the code you've posted, and that the responsibility of posting code is understood: you will get questions that you don't want to answer and you will encounter contexts where people are doing things you didn't intend.  To some extent, that is the point of putting code out into the wild.  It's hard.  But it's not my fault that your library kinda sucks and was unusable for my purposes.

But you can be polite about it!  If you spent one minute with the responses you sent, I think you'd be surprised what 2 minutes would do.

**Comment by stachenov** [comment] 2019-12-29 05:54
The library *is* poorly written. Not a big surprise since I had less than one year of coding experience when I started it.

That doesn't change the fact that your question was just as poorly written. It was impossible to understand and answer.

I guess that by this time it's pretty much a legacy library, since there are apparently better ones available. I really don't have time to turn it into a better designed and documented QuaZIP 2.0.

Still, there are people that happily use it, and although they *do* ask questions, they are usually easily answered, unlike yours.
