### ISSUE TITLE
Homebrew build from source on Mac M1 (Apple Silicon) has errors

### ISSUE THREAD

**Issue by arunkv** [stachenov/quazip#103] opened 2020-12-29 16:00 UTC
Homebrew 2.7.1
MacOS Big Sur 11.1 (20C69) arm64

Trying to build quazip from source errors out with these errors:

```
❯ brew install --build-from-source quazip
==> Downloading https://github.com/stachenov/quazip/archive/v0.9.1.tar.gz
==> qmake quazip.pro -config release PREFIX=/opt/homebrew/Cellar/quazip/0.9.1 LIBS+=-lz
==> make install
Last 15 lines from /Users/arun/Library/Logs/Homebrew/quazip/02.make:
class QFlags
      ^
/opt/homebrew/Cellar/qt/5.15.2/lib/QtCore.framework/Headers/qflags.h:89:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'int' to 'QFlags<QFileDevice::Permission> &&' for 1st argument
/opt/homebrew/Cellar/qt/5.15.2/lib/QtCore.framework/Headers/qflags.h:121:29: note: candidate constructor not viable: no known conversion from 'int' to 'QFileDevice::Permission' for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(Enum flags) noexcept : i(Int(flags)) {}
                            ^
/opt/homebrew/Cellar/qt/5.15.2/lib/QtCore.framework/Headers/qflags.h:125:29: note: candidate constructor not viable: no known conversion from 'int' to 'QFlag' for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(QFlag flag) noexcept : i(flag) {}
                            ^
/opt/homebrew/Cellar/qt/5.15.2/lib/QtCore.framework/Headers/qflags.h:127:29: note: candidate constructor not viable: no known conversion from 'int' to 'std::initializer_list<Permission>' for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(std::initializer_list<Enum> flags) noexcept
                            ^
1 error generated.
make[1]: *** [.obj/quazipfileinfo.o] Error 1
make: *** [sub-quazip-install_subtargets] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
quazip 1.1 https://github.com/Homebrew/homebrew-core/pull/67223
```

**Comment by stachenov** [comment] 2020-12-29 16:10
1. v0.9.1 is not the latest version. QuaZip migrated to CMake with 1.0 and qmake support for v0.9.x is now very limited.
2. “Last 15 lines” aren't really helpful. I can clearly see what the problem is, but I can't see at all which *QuaZip* source file has it because it's truncated.

Need to see the complete error message. But even then, all I can do is to fix the error and release, say, v0.9.2. How to make Homebrew actually use it is another question, and I can't possibly be of any help there because I haven't even *seen* a Mac in my life.

**Comment by stachenov** [comment] 2021-01-01 19:24
OK, I got it anyway. I remembered that something like that was fixed once. Found the appropriate commit and cherry-picked it into the v0.9.x branch. I can make a new release now, but it would be nice to have confirmation that it actually works.

There were numerous compatibility and deprecation fixes in 1.x, though. I'd recommend migrating to it.

**Comment by arunkv** [comment] 2021-01-01 23:13
Thanks for following up. Moved to Quazip 1.1. You can close this as "won't fix".

**Closed** 2021-01-02 08:04 UTC
